languageCode = 'es-es'
# Spanish is the default language
defaultContentLanguage = "es"
# Force to have /en/my-page and /fr/my-page routes, even for default language.
defaultContentLanguageInSubdir= true
title = 'LainWirelesss'
theme = 'learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  author = "Iván Piña Castillo"
  description = "Blog personal para mi documentación."
  showVisitedLinks = false
  disableSearch = false
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  disableShortcutsTitle = false
  disableLandingPageButton = false
  #landingPageURL = "/"
  landingPageName = "<i class='fas fa-home'></i> Inicio"
  disableLanguageSwitchingButton = false
  disableBreadcrumb = false
  disableMermaid = true
  disableNextPrev = true
  ordersectionsby = "weight"
  themeVariant = "mine"
  custom_css = ["css/foo.css", "css/bar.css"]
  titleSeparator = "-"

[markup.goldmark.renderer]
  unsafe= true

[[menu.shortcuts]]
  name = "<i class='fas fa-user'></i> Sobre mí"
  url = "about/"
  weight = 5

[[menu.shortcuts]] 
  name = "<i class='fab fa-github'></i> GitHub repo"
  identifier = "ds"
  url = "https://github.com/LainWireless"
  weight = 10

[[menu.shortcuts]]
  name = "<i class='fab fa-linkedin'></i> LinkedIn"
  url = "https://www.linkedin.com/in/ivan-pina-castillo/"
  weight = 20

[[menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Correo"
  url = "mailto: ivanpinacastillo2002@gmail.com"
  weight = 25

[[menu.shortcuts]]
  name = "<i class='fas fa-tags'></i> Tags"
  url = "tags/"
  weight = 30

[[menu.shortcuts]]
  name = "<i class='fas fa-layer-group'></i> Categorías"
  pageRef = "categories/"
  weight = 40
